spring:
  application:
    name: video-processing-pipeline
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

server:
  shutdown: graceful

springdoc:
  swagger-ui:
    path: /swagger-ui.html